-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 10:51:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_blogpessoal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_blogpessoal` ;

-- -----------------------------------------------------
-- Schema db_blogpessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_blogpessoal` DEFAULT CHARACTER SET utf8 ;
USE `db_blogpessoal` ;

-- -----------------------------------------------------
-- Table `db_blogpessoal`.`tb_temas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blogpessoal`.`tb_temas` ;

CREATE TABLE IF NOT EXISTS `db_blogpessoal`.`tb_temas` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blogpessoal`.`tb_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blogpessoal`.`tb_usuarios` ;

CREATE TABLE IF NOT EXISTS `db_blogpessoal`.`tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(5000) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blogpessoal`.`tb_postagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_blogpessoal`.`tb_postagens` ;

CREATE TABLE IF NOT EXISTS `db_blogpessoal`.`tb_postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(1000) NOT NULL,
  `titulo` VARCHAR(1000) NOT NULL,
  `datapost` VARCHAR(1000) NOT NULL,
  `autor` VARCHAR(1000) NOT NULL,
  `link` VARCHAR(1000) NOT NULL,
  `imagem` VARCHAR(1000) NOT NULL,
  `tb_categorias_id` BIGINT NOT NULL,
  `tb_acesso_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tb_categorias_id`, `tb_acesso_id`),
  INDEX `fk_tb_postagens_tb_categorias_idx` (`tb_categorias_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_acesso1_idx` (`tb_acesso_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `db_blogpessoal`.`tb_temas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_acesso1`
    FOREIGN KEY (`tb_acesso_id`)
    REFERENCES `db_blogpessoal`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
